GEOPY-855
MiraGeoscience/omf pull request #22
Opened 2023-02-14 18:59 UTC by domfournier

2023-03-08 21:23 UTC, andrewg-mira commented
This runs without error locally? Hmmmm... I'm going to try to reproduce it.

2023-03-09 17:31 UTC, benk-mira requested changes
Looks good, couple comments

2023-03-09 17:31 UTC, benk-mira commented on omf/fileio/geoh5.py
> +            #     kwargs["values"] = kwargs["values"].reshape(parent.shape)[:, :, ::-1].flatten()
cleanup

2023-03-09 17:31 UTC, benk-mira commented on omf/fileio/geoh5.py
> +        kwargs["z_cell_delimiters"] = (
`kwargs["z_cell_delimiters"] *= element.geometry.axis_w[-1]`

2023-03-10 17:24 UTC, benk-mira approved these changes
perfect!

2023-03-22 18:42 UTC, merged